parameters:
    env(FORUMIFY_URL): 'https://forumify.net'
    env(FORUMIFY_DEMO): false
    env(FORUMIFY_HOSTED_INSTANCE): false
    env(FORUMIFY_CLIENT_ID): ''
    env(FORUMIFY_CLIENT_SECRET): ''

    forumify.asset.storage.path: '/storage/assets'
    forumify.avatar.storage.path: '/storage/avatars'
    forumify.resource.storage.path: '/storage/resources'
    forumify.media.storage.path: '/storage/media'

    forumify.vendor_dir: '%kernel.project_dir%/vendor'
    forumify.project_dir: '%forumify.vendor_dir%/forumify/forumify-platform'
